### ISSUE TITLE
Error converting to JSON: Invalid header: Package file version 525 not supported

### ISSUE THREAD

**Issue by lumkit** [localcc/gvas#106]
My project shows an error when using your library: 'Error converting to JSON: Invalid header: Package file version 525 not supported.' After reviewing the source code, I found that your open-source library only supports up to version 524. Could you please add support for version 525 or higher?

this is the test file：[Active.zip](https://github.com/user-attachments/files/16039516/Active.zip)

**Comment by localcc** [comment]
Fixed as of fcffd619bee8d16aa0132a69f2a34d43acd0ceb6
