### ISSUE TITLE
bloating file size

### ISSUE THREAD

**Issue by Swarkin** [localcc/gvas#107]
Just opening a .sav file and saving it immediately after bloats the file by roughly 2x. Why is that?
The game still opens it correctly.

**Comment by scottanderson** [comment]
@Swarkin could you please zip your sav file and attach it here so we can take a look? Thanks for the report!

**Comment by Swarkin** [comment]
This is the original file, produced by the game:
[original.zip](https://github.com/user-attachments/files/16042020/original.zip)

This is the file after running the following code:
```rust
	let mut file = File::options()
		.read(true).write(true).open(PATH).unwrap();

	let gvas_file = GvasFile::read(&mut file, GameVersion::Default).unwrap();
	gvas_file.write(&mut file).unwrap();
```
[processed.zip](https://github.com/user-attachments/files/16042046/processed.zip)

More than doubling file size. The game surprisingly still reads the contents fine, my in-game inventory is populated correctly.

**Comment by Swarkin** [comment]
Hold on, it was an issue on my end. I was using the same file handle to read and write, expecting its contents to be overwritten instead of appended.
Sorry for that
