### ISSUE TITLE
File version 524 not supported

### ISSUE THREAD

**Issue by 0xS4D** [localcc/gvas#46]
Got this error:

Err(
    Deserialize(
        InvalidHeader(
            "Package file version 524 not supported",
        ),
    ),
)

on Hogwarts Legacy Save File

**Comment by localcc** [comment]
Could you attach the save file?

**Comment by 0xS4D** [comment]
[HL-01-00.zip](https://github.com/localcc/gvas/files/13778110/HL-01-00.zip)

It's from Hogwarts Legacy
