### ISSUE TITLE
Unable to open Palworld player files

### ISSUE THREAD

**Issue by xAt0mZ** [localcc/gvas#53]
Similarly to #44  I tried to open various files of the Palworld `savedGames` directory with gvas2json

However for most of the files, I'm getting various `Error: Invalid header: File type XXXX not recognized` errors (the XXX number varies for each file).
Some files like `UserOption.sav` are parsed without issues.

Is there a way to help gvas lib understand the inner format?

[files.zip](https://github.com/localcc/gvas/files/13998752/files.zip)

**Comment by localcc** [comment]
The file looks like it's compressed/encrypted, currently investigating.

**Comment by localcc** [comment]
The file uses simple zlib compression, should be fairly trivial to add support

**Comment by localcc** [comment]
The format is as follows:

<decompressed length> <compressed length> <"PlZ1" constant> <zlib stream>


Compressed length only includes the zlib stream length

**Comment by localcc** [comment]
Decompressing it as zlib only works for some files, and even then the gvas file is not read correctly by the lib, the game itself uses `FCompression::CompressMemory` for compressing the save file, will look more into it in the morning.

**Comment by trumank** [comment]
ref https://github.com/trumank/uesave-rs/issues/22

**Comment by localcc** [comment]
The game also saves most of the character data inside of an array and then serializes this into this gvas file, the array is the `RawData` field inside of the `CharacterSaveParameterMap`

**Comment by xAt0mZ** [comment]
You are a legend dude. Thanks a lot!

**Comment by xAt0mZ** [comment]
@localcc so, all files seem to be converted correctly both ways, but this one: 
[Level.zip](https://github.com/localcc/gvas/files/14002153/Level.zip)
Getting `Error: Missing hint for struct StructProperty at path worldSaveData.StructProperty.CharacterSaveParameterMap.MapProperty.Key.StructProperty, cursor position: 1773`

I built a new version of gvas2json targeting the latest main commit of this repo and temporarily fixed the code to read using `GameVersion::Palworld`.
I wish I know more about gvas and Rust to handle it by myself but unfortunately this is a bit too much for my skills...

**Comment by localcc** [comment]
You can find the required hints here https://github.com/localcc/gvas/blob/main/tests/palworld.rs

**Comment by xAt0mZ** [comment]
Thanks! I added the following 2 hints that were missing for this specific file

```rs
    (
        String::from("worldSaveData.StructProperty.WorkSaveData.ArrayProperty.WorkAssignMap.MapProperty.Value.StructProperty"),
        String::from("StructProperty")
    ), (
        String::from("worldSaveData.StructProperty.DungeonSaveData.ArrayProperty.MapObjectSaveData.ArrayProperty.ConcreteModel.StructProperty.ModuleMap.MapProperty.Value.StructProperty"),
        String::from("StructProperty")
    ),
```

However JSON format of this file is 2.94GB so I'd suggest not including it in tests 😁
